version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 10
    build:
      commands:
      - npm install
      - npm run build
      - aws s3 sync dist s3://smokymtcrn.com --delete