version: 0.1
phases:
    install:
        runtime-versions:
          nodejs: 10
        commands:
        - npm install
        - npm run build
        - aws s3 sync dist s3://smokymtcrn.com --delete